/*
This script is only used to input tags！Before you run this script, you have to migrate the initial tables
by following codes:
    ~demo/code/backend# python3 manage.py migrate                   (construct some built-in tables in django)
    ~demo/code/backend# python3 manage.py makemigrations models     (notify that the models have some changes)
    ~demo/code/backend# python3 manage.py migrate models            (handle the changes, reconstruct the data)
As you can see, we construct the tables by django rather than sql script.
And we can pleasantly manage the database by admin.app provided by django :)
e.g:  
    ~demo/code/backend# python3 manage.py runserver 127.0.0.1:8000
    then visit: 127.0.0.1:8000/admin/
*/

INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('tench');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('goldfish');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('great white shark');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('tiger shark');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('hammerhead');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('electric ray');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('stingray');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('cock');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('hen');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('ostrich');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('brambling');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('goldfinch');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('house finch');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('junco');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('indigo bunting');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('robin');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bulbul');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('jay');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('magpie');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('chickadee');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('water ouzel');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('kite');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bald eagle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('vulture');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('great grey owl');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('European fire salamander');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('common newt');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('eft');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('spotted salamander');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('axolotl');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bullfrog');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('tree frog');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('tailed frog');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('loggerhead');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('leatherback turtle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('mud turtle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('terrapin');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('box turtle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('banded gecko');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('common iguana');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('American chameleon');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('whiptail');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('agama');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('frilled lizard');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('alligator lizard');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Gila monster');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('green lizard');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('African chameleon');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Komodo dragon');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('African crocodile');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('American alligator');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('triceratops');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('thunder snake');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('ringneck snake');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('hognose snake');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('green snake');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('king snake');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('garter snake');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('water snake');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('vine snake');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('night snake');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('boa constrictor');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('rock python');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Indian cobra');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('green mamba');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('sea snake');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('horned viper');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('diamondback');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('sidewinder');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('trilobite');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('harvestman');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('scorpion');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('black and gold garden spider');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('barn spider');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('garden spider');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('black widow');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('tarantula');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('wolf spider');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('tick');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('centipede');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('black grouse');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('ptarmigan');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('ruffed grouse');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('prairie chicken');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('peacock');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('quail');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('partridge');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('African grey');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('macaw');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('sulphur-crested cockatoo');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('lorikeet');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('coucal');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bee eater');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('hornbill');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('hummingbird');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('jacamar');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('toucan');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('drake');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('red-breasted merganser');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('goose');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('black swan');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('tusker');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('echidna');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('platypus');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('wallaby');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('koala');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('wombat');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('jellyfish');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('sea anemone');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('brain coral');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('flatworm');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('nematode');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('conch');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('snail');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('slug');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('sea slug');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('chiton');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('chambered nautilus');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Dungeness crab');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('rock crab');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('fiddler crab');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('king crab');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('American lobster');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('spiny lobster');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('crayfish');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('hermit crab');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('isopod');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('white stork');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('black stork');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('spoonbill');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('flamingo');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('little blue heron');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('American egret');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bittern');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('crane');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('limpkin');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('European gallinule');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('American coot');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bustard');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('ruddy turnstone');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('red-backed sandpiper');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('redshank');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('dowitcher');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('oystercatcher');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('pelican');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('king penguin');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('albatross');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('grey whale');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('killer whale');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('dugong');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('sea lion');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Chihuahua');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Japanese spaniel');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Maltese dog');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Pekinese');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Shih-Tzu');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Blenheim spaniel');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('papillon');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('toy terrier');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Rhodesian ridgeback');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Afghan hound');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('basset');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('beagle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bloodhound');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bluetick');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('black-and-tan coonhound');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Walker hound');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('English foxhound');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('redbone');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('borzoi');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Irish wolfhound');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Italian greyhound');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('whippet');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Ibizan hound');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Norwegian elkhound');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('otterhound');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Saluki');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Scottish deerhound');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Weimaraner');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Staffordshire bullterrier');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('American Staffordshire terrier');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Bedlington terrier');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Border terrier');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Kerry blue terrier');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Irish terrier');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Norfolk terrier');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Norwich terrier');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Yorkshire terrier');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('wire-haired fox terrier');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Lakeland terrier');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Sealyham terrier');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Airedale');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('cairn');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Australian terrier');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Dandie Dinmont');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Boston bull');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('miniature schnauzer');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('giant schnauzer');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('standard schnauzer');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Scotch terrier');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Tibetan terrier');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('silky terrier');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('soft-coated wheaten terrier');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('West Highland white terrier');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Lhasa');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('flat-coated retriever');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('curly-coated retriever');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('golden retriever');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Labrador retriever');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Chesapeake Bay retriever');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('German short-haired pointer');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('vizsla');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('English setter');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Irish setter');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Gordon setter');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Brittany spaniel');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('clumber');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('English springer');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Welsh springer spaniel');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('cocker spaniel');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Sussex spaniel');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Irish water spaniel');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('kuvasz');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('schipperke');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('groenendael');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('malinois');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('briard');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('kelpie');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('komondor');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Old English sheepdog');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Shetland sheepdog');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('collie');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Border collie');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Bouvier des Flandres');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Rottweiler');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('German shepherd');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Doberman');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('miniature pinscher');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Greater Swiss Mountain dog');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Bernese mountain dog');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Appenzeller');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('EntleBucher');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('boxer');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bull mastiff');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Tibetan mastiff');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('French bulldog');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Great Dane');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Saint Bernard');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Eskimo dog');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('malamute');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Siberian husky');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('dalmatian');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('affenpinscher');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('basenji');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('pug');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Leonberg');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Newfoundland');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Great Pyrenees');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Samoyed');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Pomeranian');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('chow');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('keeshond');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Brabancon griffon');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Pembroke');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Cardigan');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('toy poodle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('miniature poodle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('standard poodle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Mexican hairless');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('timber wolf');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('white wolf');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('red wolf');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('coyote');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('dingo');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('dhole');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('African hunting dog');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('hyena');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('red fox');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('kit fox');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Arctic fox');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('grey fox');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('tabby');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('tiger cat');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Persian cat');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Siamese cat');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Egyptian cat');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('cougar');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('lynx');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('leopard');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('snow leopard');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('jaguar');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('lion');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('tiger');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('cheetah');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('brown bear');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('American black bear');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('ice bear');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('sloth bear');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('mongoose');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('meerkat');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('tiger beetle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('ladybug');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('ground beetle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('long-horned beetle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('leaf beetle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('dung beetle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('rhinoceros beetle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('weevil');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('fly');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bee');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('ant');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('grasshopper');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('cricket');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('walking stick');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('cockroach');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('mantis');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('cicada');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('leafhopper');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('lacewing');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('dragonfly');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('damselfly');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('admiral');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('ringlet');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('monarch');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('cabbage butterfly');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('sulphur butterfly');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('lycaenid');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('starfish');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('sea urchin');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('sea cucumber');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('wood rabbit');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('hare');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Angora');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('hamster');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('porcupine');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('fox squirrel');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('marmot');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('beaver');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('guinea pig');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('sorrel');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('zebra');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('hog');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('wild boar');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('warthog');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('hippopotamus');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('ox');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('water buffalo');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bison');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('ram');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bighorn');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('ibex');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('hartebeest');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('impala');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('gazelle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Arabian camel');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('llama');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('weasel');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('mink');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('polecat');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('black-footed ferret');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('otter');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('skunk');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('badger');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('armadillo');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('three-toed sloth');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('orangutan');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('gorilla');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('chimpanzee');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('gibbon');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('siamang');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('guenon');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('patas');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('baboon');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('macaque');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('langur');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('colobus');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('proboscis monkey');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('marmoset');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('capuchin');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('howler monkey');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('titi');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('spider monkey');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('squirrel monkey');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Madagascar cat');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('indri');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Indian elephant');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('African elephant');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('lesser panda');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('giant panda');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('barracouta');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('eel');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('coho');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('rock beauty');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('anemone fish');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('sturgeon');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('gar');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('lionfish');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('puffer');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('abacus');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('abaya');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('academic gown');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('accordion');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('acoustic guitar');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('aircraft carrier');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('airliner');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('airship');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('altar');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('ambulance');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('amphibian');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('analog clock');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('apiary');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('apron');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('ashcan');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('assault rifle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('backpack');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bakery');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('balance beam');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('balloon');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('ballpoint');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Band Aid');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('banjo');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bannister');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('barbell');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('barber chair');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('barbershop');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('barn');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('barometer');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('barrel');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('barrow');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('baseball');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('basketball');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bassinet');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bassoon');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bathing cap');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bath towel');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bathtub');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('beach wagon');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('beacon');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('beaker');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bearskin');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('beer bottle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('beer glass');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bell cote');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bib');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bicycle-built-for-two');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bikini');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('binder');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('binoculars');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('birdhouse');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('boathouse');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bobsled');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bolo tie');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bonnet');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bookcase');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bookshop');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bottlecap');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bow');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bow tie');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('brass');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('brassiere');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('breakwater');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('breastplate');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('broom');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bucket');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('buckle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bulletproof vest');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bullet train');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('butcher shop');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('cab');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('caldron');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('candle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('cannon');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('canoe');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('can opener');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('cardigan');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('car mirror');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('carousel');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('carpenter's kit');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('carton');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('car wheel');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('cash machine');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('cassette');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('cassette player');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('castle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('catamaran');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('CD player');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('cello');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('cellular telephone');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('chain');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('chainlink fence');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('chain mail');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('chain saw');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('chest');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('chiffonier');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('chime');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('china cabinet');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Christmas stocking');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('church');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('cinema');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('cleaver');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('cliff dwelling');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('cloak');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('clog');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('cocktail shaker');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('coffee mug');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('coffeepot');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('coil');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('combination lock');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('computer keyboard');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('confectionery');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('container ship');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('convertible');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('corkscrew');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('cornet');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('cowboy boot');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('cowboy hat');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('cradle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('crane');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('crash helmet');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('crate');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('crib');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Crock Pot');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('croquet ball');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('crutch');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('cuirass');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('dam');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('desk');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('desktop computer');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('dial telephone');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('diaper');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('digital clock');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('digital watch');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('dining table');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('dishrag');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('dishwasher');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('disk brake');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('dock');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('dogsled');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('dome');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('doormat');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('drilling platform');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('drum');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('drumstick');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('dumbbell');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Dutch oven');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('electric fan');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('electric guitar');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('electric locomotive');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('entertainment center');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('envelope');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('espresso maker');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('face powder');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('feather boa');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('file');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('fireboat');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('fire engine');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('fire screen');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('flagpole');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('flute');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('folding chair');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('football helmet');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('forklift');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('fountain');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('fountain pen');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('four-poster');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('freight car');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('French horn');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('frying pan');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('fur coat');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('garbage truck');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('gasmask');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('gas pump');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('goblet');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('go-kart');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('golf ball');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('golfcart');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('gondola');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('gong');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('gown');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('grand piano');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('greenhouse');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('grille');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('grocery store');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('guillotine');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('hair slide');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('hair spray');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('half track');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('hammer');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('hamper');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('hand blower');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('hand-held computer');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('handkerchief');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('hard disc');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('harmonica');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('harp');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('harvester');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('hatchet');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('holster');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('home theater');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('honeycomb');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('hook');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('hoopskirt');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('horizontal bar');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('horse cart');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('hourglass');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('iPod');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('iron');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('jack-o'-lantern');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('jean');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('jeep');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('jersey');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('jigsaw puzzle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('jinrikisha');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('joystick');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('kimono');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('knee pad');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('knot');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('lab coat');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('ladle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('lampshade');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('laptop');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('lawn mower');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('lens cap');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('letter opener');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('library');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('lifeboat');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('lighter');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('limousine');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('liner');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('lipstick');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Loafer');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('lotion');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('loudspeaker');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('loupe');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('lumbermill');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('magnetic compass');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('mailbag');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('mailbox');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('maillot');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('maillot');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('manhole cover');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('maraca');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('marimba');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('mask');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('matchstick');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('maypole');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('maze');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('measuring cup');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('medicine chest');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('megalith');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('microphone');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('microwave');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('military uniform');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('milk can');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('minibus');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('miniskirt');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('minivan');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('missile');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('mitten');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('mixing bowl');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('mobile home');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Model T');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('modem');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('monastery');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('monitor');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('moped');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('mortar');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('mortarboard');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('mosque');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('mosquito net');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('motor scooter');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('mountain bike');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('mountain tent');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('mouse');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('mousetrap');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('moving van');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('muzzle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('nail');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('neck brace');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('necklace');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('nipple');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('notebook');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('obelisk');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('oboe');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('ocarina');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('odometer');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('oil filter');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('organ');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('oscilloscope');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('overskirt');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('oxcart');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('oxygen mask');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('packet');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('paddle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('paddlewheel');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('padlock');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('paintbrush');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('pajama');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('palace');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('panpipe');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('paper towel');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('parachute');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('parallel bars');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('park bench');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('parking meter');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('passenger car');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('patio');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('pay-phone');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('pedestal');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('pencil box');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('pencil sharpener');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('perfume');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Petri dish');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('photocopier');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('pick');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('pickelhaube');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('picket fence');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('pickup');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('pier');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('piggy bank');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('pill bottle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('pillow');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('ping-pong ball');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('pinwheel');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('pirate');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('pitcher');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('plane');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('planetarium');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('plastic bag');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('plate rack');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('plow');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('plunger');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Polaroid camera');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('pole');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('police van');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('poncho');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('pool table');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('pop bottle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('pot');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('potter's wheel');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('power drill');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('prayer rug');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('printer');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('prison');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('projectile');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('projector');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('puck');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('punching bag');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('purse');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('quill');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('quilt');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('racer');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('racket');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('radiator');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('radio');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('radio telescope');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('rain barrel');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('recreational vehicle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('reel');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('reflex camera');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('refrigerator');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('remote control');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('restaurant');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('revolver');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('rifle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('rocking chair');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('rotisserie');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('rubber eraser');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('rugby ball');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('rule');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('running shoe');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('safe');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('safety pin');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('saltshaker');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('sandal');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('sarong');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('sax');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('scabbard');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('scale');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('school bus');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('schooner');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('scoreboard');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('screen');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('screw');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('screwdriver');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('seat belt');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('sewing machine');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('shield');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('shoe shop');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('shoji');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('shopping basket');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('shopping cart');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('shovel');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('shower cap');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('shower curtain');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('ski');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('ski mask');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('sleeping bag');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('slide rule');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('sliding door');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('slot');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('snorkel');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('snowmobile');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('snowplow');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('soap dispenser');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('soccer ball');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('sock');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('solar dish');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('sombrero');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('soup bowl');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('space bar');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('space heater');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('space shuttle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('spatula');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('speedboat');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('spider web');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('spindle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('sports car');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('spotlight');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('stage');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('steam locomotive');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('steel arch bridge');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('steel drum');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('stethoscope');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('stole');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('stone wall');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('stopwatch');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('stove');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('strainer');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('streetcar');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('stretcher');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('studio couch');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('stupa');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('submarine');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('suit');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('sundial');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('sunglass');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('sunglasses');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('sunscreen');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('suspension bridge');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('swab');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('sweatshirt');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('swimming trunks');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('swing');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('switch');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('syringe');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('table lamp');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('tank');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('tape player');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('teapot');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('teddy');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('television');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('tennis ball');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('thatch');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('theater curtain');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('thimble');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('thresher');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('throne');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('tile roof');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('toaster');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('tobacco shop');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('toilet seat');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('torch');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('totem pole');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('tow truck');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('toyshop');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('tractor');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('trailer truck');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('tray');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('trench coat');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('tricycle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('trimaran');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('tripod');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('triumphal arch');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('trolleybus');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('trombone');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('tub');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('turnstile');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('typewriter keyboard');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('umbrella');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('unicycle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('upright');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('vacuum');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('vase');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('vault');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('velvet');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('vending machine');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('vestment');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('viaduct');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('violin');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('volleyball');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('waffle iron');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('wall clock');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('wallet');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('wardrobe');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('warplane');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('washbasin');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('washer');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('water bottle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('water jug');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('water tower');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('whiskey jug');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('whistle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('wig');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('window screen');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('window shade');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('Windsor tie');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('wine bottle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('wing');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('wok');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('wooden spoon');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('wool');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('worm fence');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('wreck');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('yawl');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('yurt');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('web site');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('comic book');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('crossword puzzle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('street sign');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('traffic light');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('book jacket');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('menu');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('plate');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('guacamole');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('consomme');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('hot pot');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('trifle');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('ice cream');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('ice lolly');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('French loaf');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bagel');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('pretzel');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('cheeseburger');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('hotdog');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('mashed potato');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('head cabbage');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('broccoli');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('cauliflower');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('zucchini');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('spaghetti squash');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('acorn squash');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('butternut squash');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('cucumber');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('artichoke');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bell pepper');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('cardoon');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('mushroom');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('apple');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('strawberry');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('orange');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('lemon');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('fig');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('pineapple');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('banana');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('jackfruit');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('custard apple');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('pomegranate');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('hay');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('carbonara');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('chocolate sauce');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('dough');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('meat loaf');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('pizza');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('potpie');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('burrito');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('red wine');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('espresso');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('cup');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('eggnog');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('alp');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bubble');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('cliff');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('coral reef');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('geyser');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('lakeside');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('promontory');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('sandbar');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('seashore');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('valley');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('volcano');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('ballplayer');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('groom');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('scuba diver');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('rapeseed');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('daisy');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('yellow lady's slipper');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('corn');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('acorn');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('hip');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('buckeye');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('coral fungus');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('agaric');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('gyromitra');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('stinkhorn');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('earthstar');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('hen-of-the-woods');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('bolete');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('ear');
INSERT INTO `aibum`.`models_tag` (`name`) VALUES ('toilet tissue');

